
using System;
using System.Threading.Tasks;
using MPB;
using MPB.Droid;
using Firebase.Auth;
using Firebase.Firestore;
using Xamarin.Forms;
using System.Diagnostics;
using Android.Gms.Extensions;
using Firebase;
using Java.Util;
using Android.Content;
using System.Collections.Generic;
using static Android.Media.Session.MediaSession;
using System.Collections.ObjectModel;
using System.Linq;
using MPB.Models;
using Transaction = MPB.Models.Transaction;


[assembly: Dependency(typeof(FirestoreDroid))]
namespace MPB.Droid
{

    public class FirestoreDroid : IFirestore
    {
        public ObservableCollection<Transaction> ListTransactions { get; private set; }

        public async Task<string[]> GetData()
        {

            FirebaseFirestore database;
            string uid = FirebaseAuth.Instance.CurrentUser.Uid;
            var app = FirebaseApp.Instance;
            database = FirebaseFirestore.GetInstance(app);

            DocumentReference docRef = database.Collection("utenti").Document(uid);
            DocumentSnapshot snapshot = (DocumentSnapshot)await docRef.Get();
            String data_name = snapshot.GetString("nome");
            String data_lName = snapshot.GetString("cognome");
            String data_email = snapshot.GetString("email");

            List<string> list = new List<string>();
            list.Add(data_name);
            list.Add(data_lName);
            list.Add(data_email);
            String[] str = list.ToArray();
            return str;

        }

        public async Task<string> EditData(String name, String lastName)
        {
            try
            {

                FirebaseFirestore database;
                string uid = FirebaseAuth.Instance.CurrentUser.Uid;
                var app = FirebaseApp.Instance;
                database = FirebaseFirestore.GetInstance(app);

                DocumentReference docRef = database.Collection("utenti").Document(uid);
                if (!String.IsNullOrEmpty(name) && !String.IsNullOrEmpty(lastName))
                {
                    var task = await docRef.Update("nome", name, "cognome", lastName);
                    return task.ToString(); //.update ritorna task<void>
                }
                else return "error";
            }
            catch (Exception)
            {
                return "error";
            }
        }

        public async Task<string> AddTransaction(string category, float money)
        {
            try
            {
                FirebaseFirestore database;
                string uid = FirebaseAuth.Instance.CurrentUser.Uid;
                var app = FirebaseApp.Instance;
                database = FirebaseFirestore.GetInstance(app);
                string date = DateTime.Today.ToString("dd/MM/yyyy");
                string type = "Earnings";
                //string timestamp = DateTime.Now.ToString();



                HashMap map = new HashMap();
                map.Put("tipologia", type);
                map.Put("cifra", money);
                map.Put("categoria", category);
                map.Put("data", date);
                map.Put("createdAt", Timestamp.Now()); //per ordinare i documenti

                //(Firebase.Firestore.FieldValue.ServerTimestamp())



                DocumentReference docRef = database.Collection("utenti").Document(uid).Collection("transazioni").Document();
                var task = await docRef.Set(map);

                //Query query = database.Collection("utenti").Document(uid).Collection("transazioni").OrderBy("createdAt", Query.Direction.Ascending); //ordina lista
                return "ok";

                // Generate a reference to a new location and add some data using push()
                //DatabaseReference pushedPostRef = postsRef.push();

                // Get the unique ID generated by a push()
                //String postId = pushedPostRef.getKey();
            }
            catch (Exception e)
            {
                Debug.WriteLine($"Error:{e}");
                return "error";
            }




            /*if (name != null) {
               await docRef.Update("nome", name);
            }
            if (lastName != null)
            {
                await docRef.Update("cognome", lastName);
            }
            */

        }

        public async Task<string> AddTransaction2(string category, float money)
        {
            try
            {
                FirebaseFirestore database;
                string uid = FirebaseAuth.Instance.CurrentUser.Uid;
                var app = FirebaseApp.Instance;
                database = FirebaseFirestore.GetInstance(app);
                string date = DateTime.Today.ToString("dd/MM/yyyy");
                string type = "Outflows";

                HashMap map = new HashMap();
                map.Put("tipologia", type);
                map.Put("cifra", money);
                map.Put("categoria", category);
                map.Put("data", date);
                map.Put("createdAt", Timestamp.Now());



                DocumentReference docRef = database.Collection("utenti").Document(uid).Collection("transazioni").Document();
                var task = await docRef.Set(map);
                return "ok";

            }
            catch (Exception e)
            {
                Debug.WriteLine($"Error:{e}");
                return "error";
            }

            /*if (name != null) {
               await docRef.Update("nome", name);
            }
            if (lastName != null)
            {
                await docRef.Update("cognome", lastName);
            }
            */

        }

        public async Task<ObservableCollection<Transaction>> GetTransactions()
        {
            ObservableCollection<Transaction> ListTransactions = new ObservableCollection<Transaction>();
            FirebaseFirestore db;
            string uid = FirebaseAuth.Instance.CurrentUser.Uid;
            var app = FirebaseApp.Instance;
            db = FirebaseFirestore.GetInstance(app);
            Query allTransactionsQuery = db.Collection("utenti").Document(uid).
                Collection("transazioni").OrderBy("createdAt", Query.Direction.Ascending); //vettore lista documenti
            QuerySnapshot allTransactionsQuerySnapshot = (QuerySnapshot)await allTransactionsQuery.Get(); //vettore lista delle informazioni (dati) di ogni documento

            foreach (DocumentSnapshot documentSnapshot in allTransactionsQuerySnapshot.Documents)
            {
                ListTransactions.Add(new Transaction()
                {
                    Type = documentSnapshot.GetString("tipologia"),
                    Category = documentSnapshot.GetString("categoria"),
                    Money = (float)documentSnapshot.Get("cifra"),
                    Date = documentSnapshot.GetString("data")
                });
            }

            return ListTransactions;
        }

        public async Task<string> TotalSum()
        {
            float sum = 0;
            FirebaseFirestore db;
            string uid = FirebaseAuth.Instance.CurrentUser.Uid;
            var app = FirebaseApp.Instance;
            db = FirebaseFirestore.GetInstance(app);
            Query allTransactionsQuery = db.Collection("utenti").Document(uid).
                Collection("transazioni"); //vettore lista documenti
            QuerySnapshot allTransactionsQuerySnapshot = (QuerySnapshot)await allTransactionsQuery.Get(); //vettore lista delle informazioni (dati) di ogni documento

            foreach (DocumentSnapshot documentSnapshot in allTransactionsQuerySnapshot.Documents)
            {
                if (String.Equals(documentSnapshot.GetString("tipologia"), "Earnings"))
                {
                    sum += (float)documentSnapshot.Get("cifra");
                }
                else if (String.Equals(documentSnapshot.GetString("tipologia"), "Outflows"))
                {
                    sum -= (float)documentSnapshot.Get("cifra");
                }

            }
            string sumString;
            if (sum >= 0)
            {
                sumString = "+" + sum.ToString();
            }
            else
            {
                sumString = sum.ToString();
            }
            return sumString;

        }

        public async Task<ObservableCollection<Transaction>> GetSomeTransactions(string category)
        {
            try
            {
                ObservableCollection<Transaction> ListTransactions = new ObservableCollection<Transaction>();
                FirebaseFirestore db;
                string uid = FirebaseAuth.Instance.CurrentUser.Uid;
                var app = FirebaseApp.Instance;
                db = FirebaseFirestore.GetInstance(app);

                //prendo solo i documenti con il campo categoria uguale alla categoria selezionata
                Query allTransactionsQuery = db.Collection("utenti").Document(uid).
                    Collection("transazioni").WhereEqualTo("categoria", category).OrderBy("createdAt", Query.Direction.Ascending); //vettore lista documenti
                QuerySnapshot allTransactionsQuerySnapshot = (QuerySnapshot)await allTransactionsQuery.Get(); //vettore lista delle informazioni (dati) di ogni documento

                foreach (DocumentSnapshot documentSnapshot in allTransactionsQuerySnapshot.Documents)
                {
                    ListTransactions.Add(new Transaction()
                    {
                        Type = documentSnapshot.GetString("tipologia"),
                        Category = documentSnapshot.GetString("categoria"),
                        Money = (float)documentSnapshot.Get("cifra"),
                        Date = documentSnapshot.GetString("data")
                    });
                }

                return ListTransactions;
            }
            catch (Exception e)
            {
                Debug.WriteLine($"Error:{e}");
                return ListTransactions;
            }

        }

        public async Task<string> PartialSum(string category)
        {
            float sum = 0;
            FirebaseFirestore db;
            string uid = FirebaseAuth.Instance.CurrentUser.Uid;
            var app = FirebaseApp.Instance;
            db = FirebaseFirestore.GetInstance(app);
            Query allTransactionsQuery = db.Collection("utenti").Document(uid).
                Collection("transazioni").WhereEqualTo("categoria", category); //vettore lista documenti
            QuerySnapshot allTransactionsQuerySnapshot = (QuerySnapshot)await allTransactionsQuery.Get(); //vettore lista delle informazioni (dati) di ogni documento

            foreach (DocumentSnapshot documentSnapshot in allTransactionsQuerySnapshot.Documents)
            {
                if (String.Equals(documentSnapshot.GetString("tipologia"), "Earnings"))
                {
                    sum += (float)documentSnapshot.Get("cifra");
                }
                else if (String.Equals(documentSnapshot.GetString("tipologia"), "Outflows"))
                {
                    sum -= (float)documentSnapshot.Get("cifra");
                }

            }
            string sumString;
            if (sum >= 0)
            {
                sumString = "+" + sum.ToString();
            }
            else
            {
                sumString = sum.ToString();
            }
            return sumString;

        }




        public async Task<float> SumEarnings()
        {
            float sum = 0;
            FirebaseFirestore db;
            string uid = FirebaseAuth.Instance.CurrentUser.Uid;
            var app = FirebaseApp.Instance;
            db = FirebaseFirestore.GetInstance(app);
            Query allTransactionsQuery = db.Collection("utenti").Document(uid).
                Collection("transazioni").WhereEqualTo("tipologia", "Earnings"); //vettore lista documenti
            QuerySnapshot allTransactionsQuerySnapshot = (QuerySnapshot)await allTransactionsQuery.Get(); //vettore lista delle informazioni (dati) di ogni documento

            foreach (DocumentSnapshot documentSnapshot in allTransactionsQuerySnapshot.Documents)
            {
                sum += (float)documentSnapshot.Get("cifra");
            }

            return sum;

        }

        public async Task<float> SumOutflows()
        {
            float sum = 0;
            FirebaseFirestore db;
            string uid = FirebaseAuth.Instance.CurrentUser.Uid;
            var app = FirebaseApp.Instance;
            db = FirebaseFirestore.GetInstance(app);
            Query allTransactionsQuery = db.Collection("utenti").Document(uid).
                Collection("transazioni").WhereEqualTo("tipologia", "Outflows"); //vettore lista documenti
            QuerySnapshot allTransactionsQuerySnapshot = (QuerySnapshot)await allTransactionsQuery.Get(); //vettore lista delle informazioni (dati) di ogni documento

            foreach (DocumentSnapshot documentSnapshot in allTransactionsQuerySnapshot.Documents)
            {
                sum -= (float)documentSnapshot.Get("cifra");
            }

            return sum;

        }


    }
}

